import type { NextPage } from 'next'
import Head from 'next/head'

import { Navbar, Hero } from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next.js Code Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />
    </div>
  )
}

export default Home
